# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvm-image' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for mvvm-image
  pod 'Alamofire', '~> 4.5'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources'
  pod 'Kingfisher', '~> 4.0'


  target 'mvvm-imageTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'

  end

  target 'mvvm-imageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
